export const ITEM_LIST_REQUEST = "ITEM_LIST_REQUEST"
export const ITEM_LIST_SUCCESS = "ITEM_LIST_SUCCESS"
export const ITEM_LIST_FAIL = "ITEM_LIST_FAIL"

export const ITEM_DELETE_REQUEST = "ITEM_DELETE_REQUEST"
export const ITEM_DELETE_SUCCESS = "ITEM_DELETE_SUCCESS"
export const ITEM_DELETE_FAIL = "ITEM_DELETE_FAIL"